### ISSUE TITLE
Any plan to add an explicit software license?

### ISSUE THREAD

**Issue by danbri** [jazzsaxmafia/show_and_tell.tensorflow#1]
It would be good to know how this is licensed for potential re-use

**Comment by jazzsaxmafia** [comment]
Hi. I am not really familiar with software liscense. I want anyone use this freely, and BSD license seems to be the one. Is adding a line in readme file enough?

**Comment by danbri** [comment]
https://help.github.com/articles/open-source-licensing/ might be useful

**Comment by jazzsaxmafia** [comment]
Thank you. I just added a license file.
